name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: "3.10"
          work-dir: .
          buildozer-cmd: buidozer android debug












     
